version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - echo "Installing dependencies..."
      - cd lambdas/signup
      - pip install -r requirements.txt -t .
      - cd ../..

  build:
    commands:
      - echo "Zipping Lambda code..."
      - cd lambdas/signup
      - zip -r ../../signup.zip .
      - cd ../..
      - aws s3 cp signup.zip s3://vpc-provisioning-bucket/lambdas/signup.zip

artifacts:
  files:
    - signup.zip
  discard-paths: yes
