version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - echo "Installing dependencies for Signup Lambda..."
      - cd lambdas/signup
      - pip install -r requirements.txt -t .
      - cd ../..

      - echo "Installing dependencies for Login Lambda..."
      - cd lambdas/login
      - pip install -r requirements.txt -t .
      - cd ../..

      - echo "Installing dependencies for Confirm Lambda..."
      - cd lambdas/confirm
      - pip install -r requirements.txt -t .
      - cd ../..

  build:
    commands:
      - echo "Zipping and uploading Signup Lambda..."
      - cd lambdas/signup
      - zip -r signup.zip .
      - aws s3 rm s3://vpc-provisioning-bucket/lambdas/signup.zip || true
      - aws s3 cp signup.zip s3://vpc-provisioning-bucket/lambdas/signup.zip
      - cd ../..

      - echo "Zipping and uploading Login Lambda..."
      - cd lambdas/login
      - zip -r login.zip .
      - aws s3 rm s3://vpc-provisioning-bucket/lambdas/login.zip || true
      - aws s3 cp login.zip s3://vpc-provisioning-bucket/lambdas/login.zip
      - cd ../..

      - echo "Zipping and uploading Confirm Lambda..."
      - cd lambdas/confirm
      - zip -r confirm.zip .
      - aws s3 rm s3://vpc-provisioning-bucket/lambdas/confirm.zip || true
      - aws s3 cp confirm.zip s3://vpc-provisioning-bucket/lambdas/confirm.zip
      - cd ../..

artifacts:
  files:
    - lambdas/signup/signup.zip
    - lambdas/login/login.zip
    - lambdas/confirm/confirm.zip
