version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - echo "Installing dependencies for all Lambdas..."
      - for dir in signup login confirm createvpc; do cd lambdas/$dir && pip install -r requirements.txt -t . && cd ../..; done

build:
  commands:
    - echo "Zipping and uploading all Lambdas..."

    - cd lambdas/signup
    - zip -r ../../signup.zip .
    - cd ../..
    - aws s3 cp signup.zip s3://vpc-provisioning-bucket/lambdas/signup.zip
    - aws lambda update-function-code --function-name vpc-provisioning-signup-dev --s3-bucket vpc-provisioning-bucket --s3-key lambdas/signup.zip

    - cd lambdas/login
    - zip -r ../../login.zip .
    - cd ../..
    - aws s3 cp login.zip s3://vpc-provisioning-bucket/lambdas/login.zip
    - aws lambda update-function-code --function-name vpc-provisioning-login-dev --s3-bucket vpc-provisioning-bucket --s3-key lambdas/login.zip

    - cd lambdas/confirm
    - zip -r ../../confirm.zip .
    - cd ../..
    - aws s3 cp confirm.zip s3://vpc-provisioning-bucket/lambdas/confirm.zip
    - aws lambda update-function-code --function-name vpc-provisioning-confirm-dev --s3-bucket vpc-provisioning-bucket --s3-key lambdas/confirm.zip

    - cd lambdas/createvpc
    - zip -r ../../createvpc.zip .
    - cd ../..
    - aws s3 cp createvpc.zip s3://vpc-provisioning-bucket/lambdas/createvpc.zip
    - aws lambda update-function-code --function-name vpc-provisioning-createvpc-dev --s3-bucket vpc-provisioning-bucket --s3-key lambdas/createvpc.zip
