version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - echo "Installing dependencies..."
      - cd lambdas/signup
      - pip install -r requirements.txt -t .
  build:
    commands:
      - echo "Zipping Lambda code..."
      - zip -r signup.zip .
      - aws s3 cp signup.zip s3://vpc-provisioning-bucket/lambdas/signup.zip
artifacts:
  files:
    - lambdas/signup/signup.zip
