version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - echo "Installing dependencies for signup... "
      - cd lambdas/signup
      - pip install -r requirements.txt -t .
      - cd ../login
      - echo "Installing dependencies for login..."
      - pip install -r requirements.txt -t .
      - cd ../..

  build:
    commands:
      - echo "Zipping signup Lambda..."
      - cd lambdas/signup
      - zip -r ../../signup.zip .
      - cd ../..

      - echo "Uploading signup.zip to S3..."
      - aws s3 cp signup.zip s3://vpc-provisioning-bucket/lambdas/signup.zip

      - echo "Zipping login Lambda..."
      - cd lambdas/login
      - zip -r ../../login.zip .
      - cd ../..

      - echo "Uploading login.zip to S3..."
      - aws s3 cp login.zip s3://vpc-provisioning-bucket/lambdas/login.zip

artifacts:
  files:
    - signup.zip
    - login.zip
  discard-paths: yes
