version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - echo Installing Terraform...
      - curl -o terraform.zip https://releases.hashicorp.com/terraform/1.8.4/terraform_1.8.4_linux_amd64.zip
      - unzip terraform.zip
      - mv terraform /usr/local/bin/
      - terraform -version

  pre_build:
    commands:
      - echo Zipping Lambda functions...
      - cd lambdas/signup
      - pip install -r requirements.txt -t .
      - zip -r ../../infra/modules/lambdas/signup.zip .
      - cd ../../infra

  build:
    commands:
      - echo Running Terraform...
      - terraform init
      - terraform apply -auto-approve

artifacts:
  files:
    - infra/modules/signup.zip
