version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - echo "Installing dependencies for Signup Lambda..."
      - cd lambdas/signup
      - pip install -r requirements.txt -t .
      - cd ../..

post_build:
  commands:
    - echo "Zipping Signup Lambda..."
    - cd lambdas/signup
    - zip -r ../../signup.zip .
    - cd ../..
    - ls -la # Confirm the zip is present in root
    - echo "Uploading to S3..."
    - aws s3 rm s3://vpc-provisioning-bucket/lambdas/signup.zip || true
    - aws s3 cp signup.zip s3://vpc-provisioning-bucket/lambdas/signup.zip
    - echo "Updating Lambda..."
    - aws lambda update-function-code --function-name vpc-provisioning-signup-dev --s3-bucket vpc-provisioning-bucket --s3-key lambdas/signup.zip

artifacts:
  files:
    - signup.zip
