version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - echo "Installing dependencies for signup lambda..."
      - cd lambdas/signup
      - pip install -r requirements.txt -t .
      - cd ../..

      - echo "Installing dependencies for login lambda..."
      - cd lambdas/login
      - pip install -r requirements.txt -t .
      - cd ../..

      - echo "Installing dependencies for confirm lambda..."
      - cd lambdas/confirm
      - pip install -r requirements.txt -t .
      - cd ../..

      - echo "Installing dependencies for createvpc lambda..."
      - cd lambdas/createvpc
      - pip install -r requirements.txt -t .
      - cd ../..

  build:
    commands:
      - echo "Zipping signup lambda..."
      - cd lambdas/signup
      - zip -r ../../signup.zip .
      - cd ../..

      - echo "Zipping login lambda..."
      - cd lambdas/login
      - zip -r ../../login.zip .
      - cd ../..

      - echo "Zipping confirm lambda..."
      - cd lambdas/confirm
      - zip -r ../../confirm.zip .
      - cd ../..

      - echo "Zipping createvpc lambda..."
      - cd lambdas/createvpc
      - zip -r ../../createvpc.zip .
      - cd ../..

      - echo "Uploading signup.zip to S3..."
      - aws s3 cp signup.zip s3://vpc-provisioning-bucket/lambdas/signup.zip

      - echo "Uploading login.zip to S3..."
      - aws s3 cp login.zip s3://vpc-provisioning-bucket/lambdas/login.zip

      - echo "Uploading confirm.zip to S3..."
      - aws s3 cp confirm.zip s3://vpc-provisioning-bucket/lambdas/confirm.zip

      - echo "Uploading createvpc.zip to S3..."
      - aws s3 cp createvpc.zip s3://vpc-provisioning-bucket/lambdas/createvpc.zip

artifacts:
  files:
    - signup.zip
    - login.zip
    - confirm.zip
    - createvpc.zip
  discard-paths: yes
