version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - echo "Installing dependencies for Signup Lambda..."
      - cd lambdas/signup
      - pip install -r requirements.txt -t .
      - cd ../..

build:
  commands:
    - echo "Zipping and uploading Signup Lambda..."
    - cd lambdas/signup
    - zip -r signup.zip .
    - ls -lh signup.zip || exit 1
    - aws s3 rm s3://vpc-provisioning-bucket/lambdas/signup.zip || true
    - aws s3 cp signup.zip s3://vpc-provisioning-bucket/lambdas/signup.zip || exit 1
    - aws lambda update-function-code --function-name vpc-provisioning-signup-dev --s3-bucket vpc-provisioning-bucket --s3-key lambdas/signup.zip
    - cd ../..

artifacts:
  files:
    - lambdas/signup/signup.zip
