version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - pip install -r lambdas/signup/requirements.txt -t lambdas/signup/
      - pip install -r lambdas/login/requirements.txt -t lambdas/login/
  build:
    commands:
      - cd lambdas/signup && zip -r ../../signup.zip . && cd ../..
      - cd lambdas/login && zip -r ../../login.zip . && cd ../..
artifacts:
  files:
    - signup.zip
    - login.zip
  discard-paths: yes

post_build:
  commands:
    - aws s3 cp signup.zip s3://vpc-provisioning-bucket/lambdas/signup.zip
    - aws s3 cp login.zip s3://vpc-provisioning-bucket/lambdas/login.zip
